all_joints:
- [0]
- [1]
- [2]
- [3]
- [4]
- [5]
all_joints_names: [bodypart1, bodypart2, bodypart3, bodypart4, bodypart5, bodypart6]
batch_size: 1
cropratio: 0.4
dataset: training-datasets/iteration-0/UnaugmentedDataSet_JD_Black_BGNov28/JD_Black_BG_JD_Black_BG95shuffle1.mat
dataset_type: default
display_iters: 1000
global_scale: 0.8
init_weights: /content/DLC/JD_Black_BG/dlc-models/iteration-0/JD_Black_BGNov28-trainset95shuffle1/train/snapshot-130000
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
max_input_size: 1500
metadataset: training-datasets/iteration-0/UnaugmentedDataSet_JD_Black_BGNov28/Documentation_data-JD_Black_BG_95shuffle1.pickle
min_input_size: 64
mirror: false
multi_step:
- [0.005, 10000]
- [0.002, 17500]
- [0.001, 30000]
- [0.001, 1030000]
net_type: resnet_50
num_joints: 6
pairwise_huber_loss: false
pairwise_predict: false
partaffinityfield_predict: false
pos_dist_thresh: 17
project_path: /content/DLC/JD_Black_BG
rotation: 25
rotratio: 0.4
save_iters: 50000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
